rails/config/routes.rb
Rails.application.routes.draw do
  resources :scores

  resources :games

  resources :terms

  resources :quizzes

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'quizzes#index'
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  

end

rails/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @quizzes = Quiz.all
    respond_with(@quizzes)
  end

  def show
    respond_with(@quiz)
  end

  def new
    @quiz = Quiz.new
    respond_with(@quiz)
  end

  def edit
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.save
    respond_with(@quiz)
  end

  def update
    @quiz.update(quiz_params)
    respond_with(@quiz)
  end

  def destroy
    @quiz.destroy
    respond_with(@quiz)
  end

  private
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def quiz_params
      params.require(:quiz).permit(:qid, :title, :owner_id)
    end
end

rails/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

rails/app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qid %><br>
    <%= f.number_field :qid %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.number_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/quizzes/_quiz.html.erb
<td>
<p class="lead">
<%= quiz.title %>
</p>
</td>
<td>
<%= link_to "", new_game_path(game: {quiz_id: quiz, num_players: 1}), {title: "1 Player Game", class: "btn btn-default btn-fab btn-raised mdi-social-person"}  %>
<%= link_to "", new_game_path(game: {quiz_id: quiz, num_players: 2}), {title: "2 Player Game", class: "btn btn-default btn-fab btn-raised mdi-social-people"}  %>
</td>

rails/app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

rails/app/views/quizzes/index.html.erb
<div class="jumbotron">
    <h1>Quizzes</h1>
    <p>Choose a Quiz and start playing with a friend!</p>
</div>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Game</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= render partial: "quiz", collection: @quizzes %>
    </tr>
  </tbody>
</table>

rails/app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

rails/app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qid:</strong>
  <%= @quiz.qid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @quiz.title %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @quiz.owner_id %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>