rails/config/routes.rb
Rails.application.routes.draw do
  resources :scores

  resources :games

  resources :terms

  resources :quizzes

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'quizzes#index'
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  

end

rails/app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user, foreign_key: :player_id
  belongs_to :game
  belongs_to :quiz
end

rails/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @scores = Score.all
    respond_with(@scores)
  end

  def show
    respond_with(@score)
  end

  def new
    @score = Score.new
    respond_with(@score)
  end

  def edit
  end

  def create
    @score = Score.new(score_params)
    @score.save
    respond_with(@score)
  end

  def update
    @score.update(score_params)
    respond_with(@score)
  end

  def destroy
    @score.destroy
    respond_with(@score)
  end

  private
    def set_score
      @score = Score.find(params[:id])
    end

    def score_params
      params.require(:score).permit(:player_id, :game_id, :quiz_id, :score)
    end
end

rails/app/helpers/scores_helper.rb
module ScoresHelper
end

rails/app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :quiz_id %><br>
    <%= f.number_field :quiz_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

rails/app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Game</th>
      <th>Quiz</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.player_id %></td>
        <td><%= score.game_id %></td>
        <td><%= score.quiz_id %></td>
        <td><%= score.score %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

rails/app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

rails/app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @score.player_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @score.game_id %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @score.quiz_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>