rails/config/routes.rb
Rails.application.routes.draw do
  resources :scores

  resources :games

  resources :terms

  resources :quizzes

  get 'welcome/index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'quizzes#index'
  
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  

end

rails/app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :quiz
  
end

rails/app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @terms = Term.all
    respond_with(@terms)
  end

  def show
    respond_with(@term)
  end

  def new
    @term = Term.new
    respond_with(@term)
  end

  def edit
  end

  def create
    @term = Term.new(term_params)
    @term.save
    respond_with(@term)
  end

  def update
    @term.update(term_params)
    respond_with(@term)
  end

  def destroy
    @term.destroy
    respond_with(@term)
  end

  private
    def set_term
      @term = Term.find(params[:id])
    end

    def term_params
      params.require(:term).permit(:quiz_id, :term, :definition, :img_url, :img_width, :img_height, :rank)
    end
end

rails/app/helpers/terms_helper.rb
module TermsHelper
end

rails/app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quiz_id %><br>
    <%= f.number_field :quiz_id %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_area :term %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :img_width %><br>
    <%= f.number_field :img_width %>
  </div>
  <div class="field">
    <%= f.label :img_height %><br>
    <%= f.number_field :img_height %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

rails/app/views/terms/index.html.erb
<h1>Listing terms</h1>

<table>
  <thead>
    <tr>
      <th>Quiz</th>
      <th>Term</th>
      <th>Definition</th>
      <th>Img url</th>
      <th>Img width</th>
      <th>Img height</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terms.each do |term| %>
      <tr>
        <td><%= term.quiz_id %></td>
        <td><%= term.term %></td>
        <td><%= term.definition %></td>
        <td><%= term.img_url %></td>
        <td><%= term.img_width %></td>
        <td><%= term.img_height %></td>
        <td><%= term.rank %></td>
        <td><%= link_to 'Show', term %></td>
        <td><%= link_to 'Edit', edit_term_path(term) %></td>
        <td><%= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Term', new_term_path %>

rails/app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

rails/app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quiz:</strong>
  <%= @term.quiz_id %>
</p>

<p>
  <strong>Term:</strong>
  <%= @term.term %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @term.definition %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @term.img_url %>
</p>

<p>
  <strong>Img width:</strong>
  <%= @term.img_width %>
</p>

<p>
  <strong>Img height:</strong>
  <%= @term.img_height %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @term.rank %>
</p>

<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back', terms_path %>